queryLog:
  type: console
  fields:
  - responseReason
  - duration
upstreams:
  strategy: strict
  timeout: 5s
  groups:
    default:
      - https://dns.quad9.net/dns-query
      - https://security.cloudflare-dns.com/dns-query
bootstrapDns:
  - upstream: https://dns.quad9.net/dns-query
    ips:
      - 9.9.9.9
      - 149.112.112.112
      - 2620:fe::9
      - 2620:fe::fe
  - upstream: https://security.cloudflare-dns.com/dns-query
    ips:
      - 1.1.1.2
      - 1.0.0.2
      - 2606:4700:4700::1112
      - 2606:4700:4700::1002
blocking:
  loading:
    maxErrorsPerSource: -1
    strategy: blocking
    downloads:
      timeout: 4m
  blockType: nxDomain
  denylists:
    scamjam-combined:
      - https://assets.scamjam.app/threats/dns/scamjam-combined.txt
  clientGroupsBlock:
    default:
      - scamjam-combined
caching:
  cacheTimeNegative: 30m
ports:
  http: localhost:8080
  https: localhost:443