[service]
    log_level = "fatal"
    log_path = "ctrld.txt"
    cache_enable = false
    leak_on_upstream_failure = true

[listener]
  [listener.0]
    ip = "127.0.0.2"
    port = 53
    restricted = true

  [listener.0.policy]
    name = "localhost policy"
    networks = [
      {"network.0" = ["upstream.0"]},
  ]

    rules = [
    ]

[network]
  [network.0]
    cidrs = ["0.0.0.0/0"]
    name = "any"

[upstream]
  [upstream.0]
    endpoint = "127.0.0.2:5333"
    name = "localhost"
    timeout = 5000
    type = "legacy"
    ip_stack = "both"

  [upstream.1]
    bootstrap_ip = "1.1.1.1"
    endpoint = "https://1.1.1.1/dns-query"
    name = "allowlist bypass resolver"
    timeout = 5000
    type = "doh"
    ip_stack = "both"
